# Disable sudo to speed up the build
sudo: false

language: python
python:
  - '3.5'
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - 'pip install pytest pytest-cov'
  - 'pip install codecov'
  - 'pip install -r requirements.txt'
  - 'python setup.py install'
script:
  - 'pytest --cov-report=xml --cov=libevolve tests/'

after_success:
  - 'codecov'
