# Disable sudo to speed up the build
sudo: false

language: python

python:
  - '3.5'

install:
  - 'pip install -r requirements.txt'
  - 'pip install pytest pytest-cov'
  - 'pip install codecov'
  - 'pip install -e .[test,ci]'
  - 'python setup.py install'

script:
  - 'pytest --cov-report=xml --cov=libevolve tests'

after_success:
  - 'codecov'